apiVersion: v1
kind: Namespace
metadata:
  name: nginx-cloud-armor
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: nginx-cloud-armor
  name: nginx-cloud-armor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  namespace: nginx-cloud-armor
  name: nginx-cloud-armor
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"http":"nginx-cloud-armor"}}'
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  namespace: nginx-cloud-armor
  name: nginx-cloud-armor
spec:
  securityPolicy:
    name: nginx-cloud-armor
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-cloud-armor
  namespace: nginx-cloud-armor
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "nginx-cloud-armor"
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: nginx-cloud-armor
            port: 
              number: 80